@extends('ui::layouts.index')

@section('content-wrapper')

    <section class="hero">
        <div class="container">
            <div class="text">
                <h1>About Us</h1>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Hic sequi aperiam aliquam velit dolorem
                    ducimus
                    provident? Minus aliquid ab eos veniam expedita? Non quam quos sed at odio temporibus perspiciatis.
                </p>
            </div>
        </div>
    </section>

    <section class="about">
        <div class="container">
            <div class="row gy-5">
                <div class="col-lg-8">
                    <div class="text">

                        <h5 class="mt-4">“A VISION OF HOPE”
                        </h5>
                        <p>There are over 1000 streets in America named after Dr. Martin Luther King Jr., the slain
                            civil
                            rights leader and Nobel Peace Prize Winner. Sadly, these streets are perceived as the most
                            derelict streets in America, void of hope or acknowledgement. </p>
                        <p>This is where our story begins. Instead of neglect, the Coalition of Hope sees the streets as
                            the
                            beginning of a renaissance and the opportunity to lead the world in a movement to improve
                            the
                            quality of life for all of society. </p>
                        <p>
                            The negative perception of Kingstreets is not actually true. Reports recently have shown
                            Kingstreets to be some of the most progressive streets in minority communities. Often having
                            a
                            wide array of industry, trade, government representation, civic representation and academic
                            institutions located on them, just to name a few.
                        </p>
                        <a
                            href="http://www.kingstreets.com/cities-of-hope-and-despair/">http://www.kingstreets.com/cities-of-hope-and-despair/</a>
                        <p>In summary, Kingstreets represents the potential and possibilities of society’s ability to
                            strive
                            for greatness and the ideals of love, justice and truth. Kingstreets represents our desires
                            to
                            overcome our fears, prejudices, and imperfections. </p>
                        <p>Kingstreets gives us the opportunity to represent the best of humanity and the need to be
                            part of
                            something greater than ourselves. Kingstreets will not be complete until all streets are
                            Kingstreets!
                        </p>
                        <h5>MINISTERS & MERCHANTS </h5>
                        <h6>Brand Differentiation </h6>
                        <p>The age-old question of how does your brand stand apart from others in the eye of the
                            consumer is
                            posed. Being able to refer to a specific point in time when your brand was able to aid in
                            the
                            recovery of blighted communities across America is a substantial contribution and
                            exceptional
                            method of brand differentiation.
                        </p>
                        <h6>Long-term Thinking </h6>
                        <p>Each corporation has a unique set of needs and those needs can be effectively filled by the
                            local
                            community at a reduced cost to the corporation. By pairing the needs of corporations with
                            the
                            resources of the local community, each party will have a share in the resulting prosperity.
                        </p>
                        <h6>Customer Engagement </h6>
                        <p>There isn’t a more direct method of customer engagement than being able to view the needs of
                            the
                            community as disclosed by its members. A portion of the proprietary software collects
                            information concerning the requests and demographics of members of the community. It will
                            allow
                            corporations to view the direct requests of citizens and their basic demographic
                            information,
                            down to the zip code. The information will not have been generated by a census or
                            questionnaire
                            and it is our assertion that it
                        </p>
                        <p>will be more reliable than any internet search engine can produce.</p>
                        <h6>Employee Engagement </h6>
                        <p>Ultimately, whether your employees are relocated or locally sourced, they will end up living
                            near
                            the work site. ALLIANCE 10 offers employers the opportunity to review and project the needs
                            of
                            the community and its employees as a result. Additionally, the resource centers have
                            numerous
                            volunteer opportunities for dedicated corporate volunteers. According to CyberGrants,
                            employees
                            who volunteer are happier. As previously mentioned, employees who are happier are more
                            productive. CyberGrants also found that employees who volunteer together tend to form
                            friendships and tighter bonds. A
                            survey conducted by Office Vibe found that 58% of men and 74% of women would turn down a
                            higher
                            paying job because they liked their coworkers, translating into longer tenures and lower
                            recruitment costs. </p>
                        <h6>Community Benefits </h6>
                        <p>The ALLIANCE 10 proprietary software allows citizens to fill out a brief questionnaire that
                            identifies the needs of the person and puts them in touch with professionals and resources
                            that
                            can aid in the resolution of their issue. Individuals who are unable or do not desire to
                            access
                            the website can visit their local resource center for
                            assistance by personnel in identifying their needs and formulating a plan. Each resource
                            center
                            is equipped with case managers that are trained in motivational
                            interviewing techniques that will assist in drawing out key information and soliciting
                            participation from community members in their own positive outcomes.</p>
                        <h6>Legal Aid </h6>
                        <p>The website serves as a database of pro bono subject matter experts, attorneys for hire on a
                            sliding fee scale, and general information concerning the issues of the community. Whether a
                            person is facing divorce, criminal charges, discrimination, or any other legal issue,
                            ALLIANCE
                            10 is available to provide practical solutions to life’s legal issues.</p>
                        <a
                            href="http://www.kingstreets.com/justice-row-legal-politics/">http://www.kingstreets.com/justice-row-legal-politics/</a>
                        <p>Non-Profit Corporations and Community Development Corporations (CDC’s)
                            Connecting nonprofit organizations and CDC’s with corporate sponsors, fundraising
                            opportunities,
                            and business development tools. It is a one stop shop for start-up and established
                            nonprofits.
                            When a nonprofit enters the site, they are able to enter the area of their mission and
                            access a
                            wealth of resources to ensure the wellbeing of its beneficiaries.</p>
                        <a
                            href="http://www.kingstreets.com/non-profit-cdcs/">http://www.kingstreets.com/non-profit-cdcs/</a>
                        <h6>International Resources </h6>
                        <p>Connecting local businesses with international resources, such as oversees manufacturers and
                            call
                            centers. It allows local businesses to reap the benefits of harnessing reduced labor costs,
                            just
                            as larger corporations do. It also connects local causes with international needs. Want to
                            send
                            water to the dessert? Now it’s possible to locate unique international needs. </p>
                        <a
                            href="http://www.kingstreets.com/international-universe/">http://www.kingstreets.com/international-universe/</a>
                        <h6>Historical Societies </h6>
                        <p>Visitors are able to do everything from research their ancestry and look up historical
                            figures to
                            reading about little known facts about African American history. It is all made possible
                            through
                            the collaborative efforts of African American historical societies across the nation. </p>
                        <h6>Community Think Tanks</h6>
                        <p>This is where subject matter experts come to make a difference in their local community.
                            Connecting professionals with local societies and boards for the betterment of the
                            community.
                            Experts may start or join a panel of like credentialed and/or diverse individuals to resolve
                            an
                            agreed upon issue within the community. They may also review data concerning zip codes
                            across
                            the nation to study differing and/or common disparities. It is a hybrid of an information
                            center
                            and opportunities to effect change in their community.
                        </p>
                        <a
                            href="http://www.kingstreets.com/community-think-tank-incubator/">http://www.kingstreets.com/community-think-tank-incubator/</a>
                        <h6>Personal Development </h6>
                        <p>Our most popular services are centered our personal development. We assist with everything
                            from
                            recruitment, job coaching, resume writing, and life mapping to time management and
                            retirement
                            planning. We are committed to helping people make the most out of their lives. As previously
                            mentioned, self-sufficiency is our top priority.
                        </p>
                        <a
                            href="http://www.kingstreets.com/home-personal-development-investment/">http://www.kingstreets.com/home-personal-development-investment/</a>
                        <p>A person visiting our website is able to enter their demographic information and concerns and
                            be
                            connected with a case manager/life coach. While we hope that everyone in need of personal
                            development will visit our center for the most comprehensive form of this service, we also
                            offer
                            web applications that can assist those in need as well. </p>
                        <p>Proprietary applications such as the DayWheel tm and life mapping will assist even the most
                            conscientious professional in optimizing their efforts to accomplish more with their life.
                        </p>
                        <h6>Business Development </h6>
                        <p>All of the services available to nonprofit organizations are available to for profit
                            enterprises
                            and more. We assist with everything from concept ventures to established businesses.
                            Business
                            owners can elect to research resources online or come in and be paired with a business
                            professional that will assist in identifying resources for every facet of ensuring the
                            success
                            of their business.
                        </p>
                        <a
                            href="http://www.kingstreets.com/support-center-business-finances-news-work/">http://www.kingstreets.com/support-center-business-finances-news-work/</a>
                        <h6>Spiritual Development </h6>
                        <p>Connecting people with places of worship and spiritual leaders irrespective of religious
                            affiliation. ALLIANCE 10 aims to support your faith and spiritual development. Visiting our
                            website puts people in touch with those of like faith and also offers historical information
                            about each of the world’s roughly 4,200 religions. Whether curious or committed, our site
                            will
                            assist you in your journey.</p>
                        <a
                            href="http://www.kingstreets.com/church-soul-spiritual/">http://www.kingstreets.com/church-soul-spiritual/</a>
                        <h6>Education </h6>
                        <p>Connecting people with educational opportunities, financial resources, and research
                            opportunities. Individuals can search for learning institutions from pre-kindergarten
                            learning
                            centers to universities. The website and select resource centers will be privy to our
                            proprietary “Edutainment” series which features a unique presentation of African and
                            resulting
                            African American history to foster a positive self- image. Students will enjoy an array of
                            presentations that vary from musical performances to
                            spoken word arts. It is our firm belief that the only thing that stands between many
                            individuals
                            and prosperity is information. We intend to reduce those barriers by providing opportunities
                            to
                            learn.</p>
                        <a
                            href="http://www.kingstreets.com/education-schools-training-youth-entertainment/">http://www.kingstreets.com/education-schools-training-youth-entertainment/</a>
                        <h6>Holistic Health </h6>
                        <p>Connecting people with professionals in all manner of health fields from mental health and
                            acupuncture to herbalists and physicians. Health consists of mind, body, and soul. Financial
                            resources are also available for individuals who may not have insurance or the financial
                            resources to remain healthy.
                        </p>
                        <a
                            href="http://www.kingstreets.com/health-medical/">http://www.kingstreets.com/health-medical/</a>
                        <h6>Getting Involved </h6>
                        <p>Nothing we do would be possible without the participation of companies like yours and the
                            community at large. We need financial contributions, resources, and volunteers of varying
                            professions. To get involved you may contact the Michael Fleming at 678-508-6283
                        </p>

                    </div>
                </div>
                <div class="col-lg-4 sidebar">
                    <div class="text">
                        <h6>MIND YOUR MANNERS WITH MR LOVINGS </h6>
                        <a href="">
                            <img src="./assets/imgs/book.jpg" alt="">
                        </a>
                    </div>
                    <div class="yt-video">
                        <h6>KINGSTREETS OVERVIEW AND INTERVIEW </h6>
                        <iframe src="https://www.youtube.com/embed/YAmiNWHUAtA"
                            title="YouTube video player" frameborder="0"
                            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                            allowfullscreen></iframe>
                    </div>
                </div>
            </div>

        </div>
    </section>
@endsection
