@extends('ui::layouts.index')

@section('content-wrapper')

    <section class="hero">
        <div class="container">
            <div class="text">
                <h1>PARTNERS </h1>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Hic sequi aperiam aliquam velit dolorem
                    ducimus
                    provident? Minus aliquid ab eos veniam expedita? Non quam quos sed at odio temporibus perspiciatis.
                </p>
            </div>
        </div>
    </section>

    <section class="about">
        <div class="container">
            <div class="row gy-5">
                <div class="col-lg-8">
                    <div class="text">
                        <h5 class="mt-4">MINISTERS & MERCHANTS</h5>
                        <h6>MINISTERS & MERCHANTS </h6>
                        <p>The age-old question of how does your brand stand apart from others in the eye of the
                            consumer is posed. Being able to refer to a specific point in time when your brand was able
                            to aid in the recovery of blighted communities across America is a substantial contribution
                            and exceptional method of brand differentiation.
                        </p>

                        <h6>Long-term Thinking </h6>
                        <p>Each corporation has a unique set of needs and those needs can be effectively filled by the
                            local community at a reduced cost to the corporation. By pairing the needs of corporations
                            with the resources of the local community, each party will have a share in the resulting
                            prosperity.
                        </p>
                        <h6>Customer Engagement </h6>
                        <p>There isn’t a more direct method of customer engagement than being able to view the needs of
                            the community as disclosed by its members. A portion of the proprietary software collects
                            information concerning the requests and demographics of members of the community. It will
                            allow corporations to view the direct requests of citizens and their basic demographic
                            information, down to the zip code. The information will not have been generated by a census
                            or questionnaire and it is our assertion that it
                        </p>
                        <p>will be more reliable than any internet search engine can produce. </p>
                        <h6>Employee Engagement </h6>
                        <p>Ultimately, whether your employees are relocated or locally sourced, they will end up living
                            near the work site. ALLIANCE 10 offers employers the opportunity to review and project the
                            needs of the community and its employees as a result. Additionally, the resource centers
                            have numerous volunteer opportunities for dedicated corporate volunteers. According to
                            CyberGrants, employees who volunteer are happier. As previously mentioned, employees who are
                            happier are more productive. CyberGrants
                            also found that employees who volunteer together tend to form friendships and tighter bonds.
                            A survey conducted by Office Vibe found that 58% of men and 74% of women would turn down a
                            higher paying job because they liked their coworkers, translating into longer tenures and
                            lower recruitment costs.</p>
                        <h6>Community Benefits </h6>
                        <p>The ALLIANCE 10 proprietary software allows citizens to fill out a brief questionnaire that
                            identifies the needs of the person and puts them in touch with professionals and resources
                            that can aid in the resolution of their issue. Individuals who are unable or do not desire
                            to access the website can visit their local resource center for
                            assistance by personnel in identifying their needs and formulating a plan. Each resource
                            center is equipped with case managers that are trained in motivational
                            interviewing techniques that will assist in drawing out key information and soliciting
                            participation from community members in their own positive outcomes.</p>
                        <h6>Legal Aid </h6>
                        <p>The website serves as a database of pro bono subject matter experts, attorneys for hire on a
                            sliding fee scale, and general information concerning the issues of the community. Whether a
                            person is facing divorce, criminal charges, discrimination, or any other legal issue,
                            ALLIANCE 10 is available to provide practical solutions to life’s legal issues.
                        </p>
                        <h6>Non-Profit Corporations and Community Development Corporations (CDC’s) </h6>
                        <p>Connecting nonprofit organizations and CDC’s with corporate sponsors, fundraising
                            opportunities, and business development tools. It is a one stop shop for start-up and
                            established nonprofits. When a nonprofit enters the site, they are able to enter the area of
                            their mission and access a wealth of resources to ensure the wellbeing of its beneficiaries.
                        </p>
                        <h6>International Resources </h6>
                        <p>Connecting local businesses with international resources, such as oversees manufacturers and
                            call centers. It allows local businesses to reap the benefits of harnessing reduced labor
                            costs, just as larger corporations do. It also connects local causes with international
                            needs. Want to send water to the dessert? Now it’s possible to locate unique international
                            needs.
                        </p>
                        <h6>Historical Societies </h6>
                        <p>Visitors are able to do everything from research their ancestry and look up historical
                            figures to reading about little known facts about African American history. It is all made
                            possible through the collaborative efforts of African American historical societies across
                            the nation.
                        </p>
                        <h6>Community Think Tanks </h6>
                        <p>This is where subject matter experts come to make a difference in their local community.
                            Connecting professionals with local societies and boards for the betterment of the
                            community. Experts may start or join a panel of like credentialed and/or diverse individuals
                            to resolve an agreed upon issue within the community. They may also review data concerning
                            zip codes across the nation to study differing and/or common disparities. It is a hybrid of
                            an information center and opportunities to effect change in their
                            community.</p>
                        <h6>Personal Development </h6>
                        <p>Our most popular services are centered our personal development. We assist with everything
                            from recruitment, job coaching, resume writing, and life mapping to time management and
                            retirement planning. We are committed to helping people make the most out of their lives. As
                            previously mentioned, self-sufficiency is our top priority.
                        </p>
                        <p>A person visiting our website is able to enter their demographic information and concerns and
                            be connected with a case manager/life coach. While we hope that everyone in need of personal
                            development will visit our center for the most comprehensive form of this service, we also
                            offer web applications that can assist those in need as well.
                        </p>
                        <p>Proprietary applications such as the DayWheel tm and life mapping will assist even the most
                            conscientious professional in optimizing their efforts to accomplish more with their life.
                        </p>
                        <h6>Business Development </h6>
                        <p>All of the services available to nonprofit organizations are available to for profit
                            enterprises and more. We assist with everything from concept ventures to established
                            businesses. Business owners can elect to research resources online or come in and be paired
                            with a business professional that will assist in identifying resources for every facet of
                            ensuring the success of their business.
                        </p>
                        <h6>Spiritual Development </h6>
                        <p>Connecting people with places of worship and spiritual leaders irrespective of religious
                            affiliation. ALLIANCE 10 aims to support your faith and spiritual development. Visiting our
                            website puts people in touch with those of like faith and also offers historical information
                            about each of the world’s roughly 4,200 religions. Whether curious or committed, our site
                            will assist you in your journey.
                        </p>
                        <h6>Education </h6>
                        <p>Connecting people with educational opportunities, financial resources, and research
                            opportunities. Individuals can search for learning institutions from pre-kindergarten
                            learning centers to universities. The website and select resource centers will be privy to
                            our proprietary “Edutainment” series which features a unique presentation of African and
                            resulting African American history to foster a positive self- image. Students will enjoy an
                            array of presentations that vary from musical performances to
                            spoken word arts. It is our firm belief that the only thing that stands between many
                            individuals and prosperity is information. We intend to reduce those barriers by providing
                            opportunities to learn.</p>
                        <h6>Holistic Health </h6>
                        <p>Connecting people with professionals in all manner of health fields from mental health and
                            acupuncture to herbalists and physicians. Health consists of mind, body, and soul. Financial
                            resources are also available for individuals who may not have insurance or the financial
                            resources to remain healthy.
                        </p>
                        <h6>Getting Involved </h6>
                        <p>Nothing we do would be possible without the participation of companies like yours and the
                            community at large. We need financial contributions, resources, and volunteers of varying
                            professions. To get involved you may contact the Michael Fleming at 678-508-6283
                        </p>
                        <h6>SOFTWARE AND APPS SOLUTIONS: (DAYWHEEL, VISION QUEST, OPERATIONS SOFTWARE, ETC.)</h6>
                        <p><a
                                href="https://www.youtube.com/watch?v=1-mct0JtRgA&t=5s">https://www.youtube.com/watch?v=1-mct0JtRgA&t=5s</a>
                            (OPERATIONS ORG CHART INSTRUCTIONS)</p>
                        <p><a href="https://www.youtube.com/watch?v=PZciQVqE3mw" target="_blank"
                                rel="noreferrer noopener">https://www.youtube.com/watch?v=PZciQVqE3mw</a>&nbsp;&nbsp;(DAYWHEEL
                            INSTRUCTIONS VIDEO COMMERCIAL)</p>
                        <p><a href="https://www.youtube.com/watch?v=MFFYWkK2YpU&amp;t=2s" target="_blank"
                                rel="noreferrer noopener">https://www.youtube.com/watch?v=MFFYWkK2YpU&amp;t=2s</a>&nbsp;(DayWheel)
                        </p>
                        <p><a href="https://www.youtube.com/watch?v=Y7pDkzHsuQE" target="_blank"
                                rel="noreferrer noopener">https://www.youtube.com/watch?v=Y7pDkzHsuQE</a>&nbsp;(DAYWHEEL
                            INSTRUCTIONS VIDEO COMMERCIAL)</p>
                        <p><a href="https://www.youtube.com/watch?v=6PJnSpbdBDo&amp;t=9s" target="_blank"
                                rel="noreferrer noopener">https://www.youtube.com/watch?v=6PJnSpbdBDo&amp;t=9s</a>&nbsp;(Vision
                            Quest and Vision Mapping Software)</p>
                        <p><a href="https://www.youtube.com/watch?v=J62ttrFRgho&amp;t=25s" target="_blank"
                                rel="noreferrer noopener">https://www.youtube.com/watch?v=J62ttrFRgho&amp;t=25s</a>&nbsp;(DayWheel
                            App Instructions)</p>
                        <p><a href="https://www.youtube.com/watch?v=m6i3n4xVfEU&amp;t=71s" target="_blank"
                                rel="noreferrer noopener">https://www.youtube.com/watch?v=m6i3n4xVfEU&amp;t=71s</a>&nbsp;(DayWheel
                            Website phone instructions)</p>
                        <p><a href="https://www.youtube.com/watch?v=tOlxd7gXfSU&amp;t=3s" target="_blank"
                                rel="noreferrer noopener">https://www.youtube.com/watch?v=tOlxd7gXfSU&amp;t=3s</a>&nbsp;(DayWheel
                            instructions video)</p>
                        <p><a href="https://www.youtube.com/watch?v=UtdaTwqnBKk" target="_blank"
                                rel="noreferrer noopener">https://www.youtube.com/watch?v=UtdaTwqnBKk</a>&nbsp;&nbsp;(DayWheel
                            instructions video)</p>
                        <h6>CARE ALLIANCE AND KINGSTREETS VIDEOS: </h6>
                        <p><a href="https://www.youtube.com/watch?v=JB2Bl_080wU&amp;t=6s" target="_blank"
                                rel="noreferrer noopener">https://www.youtube.com/watch?v=JB2Bl_080wU&amp;t=6s</a>(Care
                            Alliance)</p>
                        <p><a href="https://www.youtube.com/watch?v=QeNxaEm-Kqs&amp;t=7s" target="_blank"
                                rel="noreferrer noopener">https://www.youtube.com/watch?v=QeNxaEm-Kqs&amp;t=7s</a>&nbsp;&nbsp;(Kingstreets)
                        </p>
                        <p><a href="https://www.youtube.com/watch?v=D2Kdr15Yl0s&amp;t=1s" target="_blank"
                                rel="noreferrer noopener">https://www.youtube.com/watch?v=D2Kdr15Yl0s&amp;t=1s</a>&nbsp;&nbsp;(Care
                            Alliance)</p>
                        <h6>MENTORING AND RESOURCE VIDEOS </h6>
                        <p><a href="https://www.youtube.com/watch?v=1-ZMvwoAUEQ&amp;t=253s" target="_blank"
                                rel="noreferrer noopener">https://www.youtube.com/watch?v=1-ZMvwoAUEQ&amp;t=253s</a>&nbsp;(Becoming
                            Tech Savvy)</p>
                        <p><a href="https://www.youtube.com/watch?v=oWevEpxqqhY&amp;t=111s" target="_blank"
                                rel="noreferrer noopener">https://www.youtube.com/watch?v=oWevEpxqqhY&amp;t=111s</a>&nbsp;&nbsp;(Career
                            and mentoring options)</p>
                        <p><a href="https://www.youtube.com/watch?v=b7Llehy-Rg4" target="_blank"
                                rel="noreferrer noopener">https://www.youtube.com/watch?v=b7Llehy-Rg4</a>&nbsp;(Mentoring)
                        </p>
                        <p><a href="https://www.youtube.com/watch?v=o3VUh0N4rq0" target="_blank"
                                rel="noreferrer noopener">https://www.youtube.com/watch?v=o3VUh0N4rq0</a>&nbsp;(Mentoring)
                        </p>
                        <p><a href="https://www.youtube.com/watch?v=pM-5lmv_Glc" target="_blank"
                                rel="noreferrer noopener">https://www.youtube.com/watch?v=pM-5lmv_Glc</a>&nbsp;(Mentoring)
                        </p>
                        <p><a href="https://www.youtube.com/watch?v=yfL_znhhh1k" target="_blank"
                                rel="noreferrer noopener">https://www.youtube.com/watch?v=yfL_znhhh1k</a>&nbsp;(Mentoring)
                        </p>
                        <p><a href="https://www.youtube.com/watch?v=4faG-HGGuA4" target="_blank"
                                rel="noreferrer noopener">https://www.youtube.com/watch?v=4faG-HGGuA4</a>&nbsp;(Mentoring)
                        </p>
                        <p><a href="https://www.youtube.com/watch?v=yfxo4M0RRjQ" target="_blank"
                                rel="noreferrer noopener">https://www.youtube.com/watch?v=yfxo4M0RRjQ</a>&nbsp;(Mentoring)
                        </p>
                        <p><a href="https://www.youtube.com/watch?v=ORf4PMwI2qk" target="_blank"
                                rel="noreferrer noopener">https://www.youtube.com/watch?v=ORf4PMwI2qk</a>&nbsp;(Project
                            Grad Mentoring)</p>
                        <p><a href="https://www.youtube.com/watch?v=v0ditafwYPo&amp;t=11s" target="_blank"
                                rel="noreferrer noopener">https://www.youtube.com/watch?v=v0ditafwYPo&amp;t=11s</a>&nbsp;(Project
                            Grad Mentoring)</p>
                        <p><a href="https://www.youtube.com/watch?v=hMyj-8nAo2U&amp;t=120s" target="_blank"
                                rel="noreferrer noopener">https://www.youtube.com/watch?v=hMyj-8nAo2U&amp;t=120s</a>&nbsp;(MAYOR
                            FRANKLIN YOUTH MENTORING)</p>
                        <h6>GOVERNMENT CONTRACTING VIDEOS: </h6>
                        <p><a href="https://www.youtube.com/watch?v=QVvswqIhsrE&amp;t=1683s" target="_blank"
                                rel="noreferrer noopener">https://www.youtube.com/watch?v=QVvswqIhsrE&amp;t=1683s</a>(Government
                            Contracting)</p>
                        <p><a href="https://www.youtube.com/watch?v=h8DNLkvAStk&amp;t=32s" target="_blank"
                                rel="noreferrer noopener">https://www.youtube.com/watch?v=h8DNLkvAStk&amp;t=32s</a>&nbsp;&nbsp;(Government
                            Contracting)</p>
                        <p><a href="https://uah.hosted.panopto.com/Panopto/Pages/Viewer.aspx?tid=a0a668dc-dac7-4521-9f99-a8e300ed0343"
                                target="_blank"
                                rel="noreferrer noopener">https://uah.hosted.panopto.com/Panopto/Pages/Viewer.aspx?tid=a0a668dc-dac7-4521-9f99-a8e300ed0343</a>&nbsp;&nbsp;(Government
                            Contracting)</p>
                        <p><a href="https://www.youtube.com/watch?v=oA8UqL22sM0&amp;t=1706s" target="_blank"
                                rel="noreferrer noopener">https://www.youtube.com/watch?v=oA8UqL22sM0&amp;t=1706s</a>&nbsp;&nbsp;(Government
                            Contracting)</p>
                        <p><a href="https://www.youtube.com/watch?v=BkuJ1gdYXiM" target="_blank"
                                rel="noreferrer noopener">https://www.youtube.com/watch?v=BkuJ1gdYXiM</a>&nbsp;&nbsp;(Government
                            Contracting)</p>
                    </div>
                </div>
                <div class="col-lg-4 sidebar">
                    <div class="text">
                        <h6>MIND YOUR MANNERS WITH MR LOVINGS </h6>
                        <a href="">
                            <img src="./assets/imgs/book.jpg" alt="">
                        </a>
                    </div>
                    <div class="yt-video">
                        <h6>KINGSTREETS OVERVIEW AND INTERVIEW </h6>
                        <iframe src="https://www.youtube.com/embed/YAmiNWHUAtA" title="YouTube video player"
                            frameborder="0"
                            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                            allowfullscreen></iframe>
                    </div>
                </div>
            </div>

        </div>
    </section>
@endsection
